# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image: 
  repository: ghcr.io/ewei2406/smartohws
  tag: "1.0.1"
  pullPolicy: Always
  port: 80

host:
  port: 30080

healthcheck:
  path: "/healthz"