apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "forgemc.fullname" . }}-backups-pvc
  labels:
    {{- include "forgemc.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backups.storage }}
  volumeName: {{ include "forgemc.fullname" . }}-backups-pv