apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "forgemc.fullname" . }}-backups-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.backups.hostPath }}
  claimRef:
    name: {{ include "forgemc.fullname" . }}-backups-pvc
    namespace: {{ .Release.Namespace }}