apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cardsim.fullname" . }}
  labels:
    {{- include "cardsim.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cardsim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cardsim.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: cardsim
          image: ghcr.io/ewei2406/cardsim:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              hostPort: 30075
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http