apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}-backups-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backups.storage }}
