apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}-backups-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.backups.hostPath }}
