apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}
  labels:
    {{- include "ftb-stoneblock.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ftb-stoneblock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftb-stoneblock.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
        - name: world-storage
          persistentVolumeClaim:
            claimName: {{ include "ftb-stoneblock.fullname" . }}-world-pvc
      containers:
        - name: ftb-stoneblock
          image: ghcr.io/ewei2406/ftb-stoneblock:1.1
          ports:
            - containerPort: 25565
              hostPort: 30065
              name: "minecraft"
          volumeMounts:
            - mountPath: "/world"
              name: world-storage