apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}
  labels:
    app.kubernetes.io/name: ftb-stoneblock
    app: ftb-stoneblock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftb-stoneblock
  template:
    metadata:
      labels:
        app: ftb-stoneblock
    spec:
      volumes:
        - name: world-storage
          persistentVolumeClaim:
            claimName: {{ include "ftb-stoneblock.fullname" . }}-world-pvc
      containers:
        - name: ftb-stoneblock
          image: ghcr.io/ewei2406/ftb-stoneblock:1.1
          ports:
            - containerPort: 25565
              name: "minecraft"
          volumeMounts:
            - mountPath: "/world"
              name: world-storage