apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}-world-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
