apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}-world-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.pv.hostPath }}
    type: Directory
