apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}
  labels:
    {{- include "ftb-stoneblock.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - name: tcp-minecraft
      protocol: TCP
      port: 25565  # The port that the service will expose
      targetPort: 25565  # The port on the container that the service will forward traffic to
      nodePort: 30065  # The port on the node that will be exposed
    - name: udp-minecraft
      protocol: UDP
      port: 25565  # The same port exposed for UDP traffic
      targetPort: 25565  # The same port on the container
      nodePort: 30065  # The port on the node that will be exposed
  selector:
    {{- include "ftb-stoneblock.selectorLabels" . | nindent 4 }}
