apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}-world-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.world.hostPath }}
  claimRef:
    name: {{ include "ftb-stoneblock.fullname" . }}-world-pvc
    namespace: {{ .Release.Namespace }}
