apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ftb-stoneblock.fullname" . }}-world-pvc
  labels:
    {{- include "ftb-stoneblock.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.world.storage }}
  volumeName: {{ include "ftb-stoneblock.fullname" . }}-world-pv